config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	#### admin
	#resources :admins
	get 'admins', to: 'admins#index'
	get 'admins/:id', to: 'admins#show', :as => "admin"
	# get 'admins/login', to: 'admins#new'
	# post 'admins/login', to: 'admins#create'
	get 'admins/:id/edit', to: 'admins#edit', :as => "edit_admin"
	patch 'admins/:id', to: 'admins#update'
	delete 'admins/:id', to: 'admins#destroy'

	# login
	get 'login', to: 'admins#login'
	post 'login', to: 'admins#login_create'
	get 'logout', to: 'admins#logout_destroy'
	# -------------------
	#### user
	resources :users
	# match ':users(/:destroy(/:id(.:format)))', via: [:delete]
	match 'users/:id',   :to => 'users#destroy',  :via => 'delete'
	# delete 'users/:id', to: 'users#fuck', :as => "user_fuck"
	# login
	get 'login/users', to: 'users#login', :as => "user_login"
	post 'login/users', to: 'users#login_create'
	get 'logout/users', to: 'users#logout_destroy'
	# -------------------
	#### post
	# resources :posts do
	# 	#### comments
	# 	resources :comments
	# end
	resources :posts

	#### comments
	resources :comments

end

app/views/admins/_form.html.erb
<div class='well'>

<!-- form_for方法用於產生一個form表單 -->
<%= form_for(@admin) do |f| %>

  <% if @admin.errors.any? %>
    <div id="error_explanation">

      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <!-- 丟參數概念定義class -->
    <%= f.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password%>
  </div>
  <br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>

<% end %>

</div>

app/views/admins/_formtag.html.erb
<div class="well">

  <%#= form_tag '/Admins_login' do %>
  <%= form_tag '/login' do %>
    <div class="form-group">
      <%= label_tag :name %>
      <br>
      <%= text_field_tag :name, params[:name] %>
    </div>

    <div class="form-group">
      <%= label_tag :password %>
      <br>
      <%= password_field_tag :password, params[:password] %>
    </div>

    <br>
    <%= submit_tag "登入", class: "btn btn-success" %>
  <% end %>
</div>

app/views/admins/edit.html.erb
<%= render 'shared/title', title: 'Edit Admin' %> 

<!-- render呼叫_form.html.erb， -->
<%= render 'form' %>
<%#= render 'shared/form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'shared/title', title: 'Who is Admins?' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Password</th> -->
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <!-- <td><%#= admin.password_digest %></td> -->

        
        <td>
          <%= link_to 'Show', 
              admin_path(admin)
          %>
        </td> 

        <!-- from here to add front-end judgement -->
        <% if admin_logged_in? %>
          <td>
          <%= link_to 'Edit',
              edit_admin_path(admin) 
          %>     
          </td>


          <!-- method delete分辨出不同 -->
          <td>
            <%= link_to 'Delete',
                admin_path(admin),
                method: :delete,
                data: { confirm: 'Are you sure?' } 
            %> 
          </td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admins/login.html.erb
<%= render 'shared/title', title: 'Admin Login' %> 

<%= render 'formtag' %>

<%= link_to 'Back', admins_path %>

app/views/admins/new.html.erb
<!-- new方法之後不能用 -->
<!-- 故 new temp也不會再用 -->
<%#= render 'shared/title', title: 'New Admin' %> 

<!-- render呼叫_form.html.erb， -->
<%#= render 'shared/form', admin: @admin %>

<%#= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<!-- 加入管理者照片 -->


<%= link_to 'Back', admins_path %>