config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	#### admin
	#resources :admins
	get 'admins', to: 'admins#index'
	get 'admins/:id', to: 'admins#show', :as => "admin"
	# get 'admins/login', to: 'admins#new'
	# post 'admins/login', to: 'admins#create'
	get 'admins/:id/edit', to: 'admins#edit', :as => "edit_admin"
	patch 'admins/:id', to: 'admins#update'
	delete 'admins/:id', to: 'admins#destroy'

	# login
	get 'login', to: 'admins#login'
	post 'login', to: 'admins#login_create'
	get 'logout', to: 'admins#logout_destroy'
	# -------------------
	#### user
	resources :users
	# match ':users(/:destroy(/:id(.:format)))', via: [:delete]
	match 'users/:id',   :to => 'users#destroy',  :via => 'delete'
	# delete 'users/:id', to: 'users#fuck', :as => "user_fuck"
	# login
	get 'login/users', to: 'users#login', :as => "user_login"
	post 'login/users', to: 'users#login_create'
	get 'logout/users', to: 'users#logout_destroy'
	# -------------------
	#### post
	# resources :posts do
	# 	#### comments
	# 	resources :comments
	# end
	resources :posts

	#### comments
	resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    # binding.pry
    @comment = Comment.new

  end

  def create

    #insert user_id into comment_params hash
    # @comment_params=comment_params
    # @user = User.find(session[:user_id])
    # @comment_params[:user_id] = @user.id
    #binding.pry
    #@user = comment.find(params[:id]).user
    @comment_params = comment_params
    @comment_params[:user_id] = User.find(session[:user_id]).id
    @comment = Comment.new(@comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@comment.post_id), notice: 'comment was successfully created.' }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to comments_path, notice: 'comment was successfully updated.' }
      end
    else
      respond_to do |format|
        format.html { render :edit, notice: 'Please update again.' }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_path, notice: 'comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:reply, :post_id)
  end

end

app/views/comments/_form.html.erb
<div id="footer" class="wrapper style2">
      <div class="container">
        <section>
          <header class="major">
            <h2>Any Comment want to say？</h2>
            <span class="byline">Come on！Share everyone right now</span>
          </header>
			
		  <%#= form_for(@post) do |f| %>	
          <%= form_for(@comment) do |f| %>
 
            <div class="row half">
              <div class="12u">
              <%= f.label :reply %>
              <%= f.text_field :reply %>
                <!-- <input class="text" type="text" name="name" id="name" placeholder="Title" /> -->
              </div>
            </div>

            <div class="row half">
              <div class="12u">
              <%= f.label 'which Post ID?' %>
              <%= f.text_field :post_id %>
                <!-- <input class="text" type="text" name="name" id="name" placeholder="Title" /> -->
              </div>
            </div>

    
            <!-- <div class="row half">
              <div class="12u"> -->
              <%#= f.label 'who u r' %>
              <%#= f.text_field :user_id  %>
                <!-- <input class="text" type="text" name="name" id="name" placeholder="Title" /> -->
              <!-- </div> -->
            <!-- </div> -->

            <div class="row half">
              <div class="12u">
                <ul class="actions">
                  <li>
                    <%= f.submit  %>
                    <!-- <input type="submit" value="comment" class="button alt" /> -->
                  </li>
                </ul>
              </div>
            </div>
          <!-- </form> -->
          <% end %>

        </section>
      </div>
    </div>

app/views/comments/index.html.erb
<%#= link_to("Index", "http://localhost:3000/posts", method: :index)%>
<%= link_to('Click here', controller: 'posts',
        action: 'index', message: 'Welcome!') %>

app/views/comments/new.html.erb
<%= render 'shared/title', title: 'Comment New' %> 

<%= render 'form'%>

<%#= link_to 'Back', post_path(@post) %>

app/views/comments/show.html.erb
<p>
   <h2><%= @post.title %></h2><br>
   <div>
   	<h5><%= @post.content %><h5>
   </div><br>


</p>

<!-- 加入管理者照片 -->

<%#= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Edit', edit_post_path %>
<%= link_to 'Delete', posts_path(@post.id),
	method: :delete,
    data: { confirm: 'Are you sure?' } 
%>

<%= link_to 'Back', posts_path %>