config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	#### admin
	#resources :admins
	get 'admins', to: 'admins#index'
	get 'admins/:id', to: 'admins#show', :as => "admin"
	# get 'admins/login', to: 'admins#new'
	# post 'admins/login', to: 'admins#create'
	get 'admins/:id/edit', to: 'admins#edit', :as => "edit_admin"
	patch 'admins/:id', to: 'admins#update'
	delete 'admins/:id', to: 'admins#destroy'

	# login
	get 'login', to: 'admins#login'
	post 'login', to: 'admins#login_create'
	get 'logout', to: 'admins#logout_destroy'
	# -------------------
	#### user
	resources :users
	# match ':users(/:destroy(/:id(.:format)))', via: [:delete]
	match 'users/:id',   :to => 'users#destroy',  :via => 'delete'
	# delete 'users/:id', to: 'users#fuck', :as => "user_fuck"
	# login
	get 'login/users', to: 'users#login', :as => "user_login"
	post 'login/users', to: 'users#login_create'
	get 'logout/users', to: 'users#logout_destroy'
	# -------------------
	#### post
	# resources :posts do
	# 	#### comments
	# 	resources :comments
	# end
	resources :posts

	#### comments
	resources :comments

end

app/models/user.rb
class User < ActiveRecord::Base
	###User
	# Tom,1111
	# Jason,22223

	has_many :posts
	has_many :comments

	has_secure_password validation: false
	
	# presence
	validates :name, presence: true
	# validates :password_digest, presence: true

	# length

	validates :name, length: { minimum: 2 }
	validates :name, length: { maximum: 200 }

	# validates :password_digest, length: { minimum: 4 }
	# validates :password_digest, length: { maximum: 10 }

	# unique
	validates :name, uniqueness: true
	# validates :password_digest, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    #binding.pry
    # @params=params.require(:user).permit(:name, :email, :phone, :password_digest)
    # user_params={
    #   name:@params[:name],
    #   email:@params[:email],
    #   phone:@params[:phone],
    #   password:@user.authenticate(@params[:password_digest])
    # }
    @user = User.new(user_params)
    if @user.save
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      end
    else
      render :new
    end
  end

  def login
  end

  def login_create

    @user = User.find_by(name: params[:name])   
    #binding.pry
    if @user &&  @user.authenticate(params[:password])

      session[:user_id] = @user.id

      respond_to do |format|
        format.html { redirect_to users_path, notice: 'user successfully logined.' }
      end

    else
      render :login
    end
  end

  def logout_destroy
    session[:user_id] = nil
    render :login
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
      end
    else
      respond_to do |format|
        format.html { render :edit, notice: 'Please update again.' }
      end
      # render :edit
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :phone, :password)
    # params.require(:user).permit(:name, :email, :phone, :password_confirmation)
  end

end

app/views/users/_form.html.erb
<div class='well'>

<!-- form_for方法用於產生一個form表單 -->
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">

      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <!-- 丟參數概念定義class -->
    <%= f.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <br>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <br>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password%>
  </div>
  <br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>

<% end %>

</div>

app/views/users/_formtag.html.erb
<div class="well">

  <%#= form_tag '/Admins_login' do %>
  <%= form_tag(login_users_path) do %>
    <div class="form-group">
      <%= label_tag :name %>
      <br>
      <%= text_field_tag :name, params[:name] %>
    </div>

    <div class="form-group">
      <%= label_tag :password %>
      <br>
      <%= password_field_tag :password, params[:password] %>
    </div>

    <br>
    <%= submit_tag "登入", class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/title', title: 'Edit User' %> 

<!-- render呼叫_form.html.erb， -->
<%= render 'form' %>
<%#= render 'shared/form', admin: @admin %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'shared/title', title: 'Welcome all User' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <!-- <th>Password</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <!-- 後續可以考慮拿掉 -->
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        
        

        <!-- from here to add front-end judgement -->
        <% if user_logged_in? %>
          <td>
            <%= link_to 'Show', 
                user_path(user)
            %>
          </td> 

          <td>
          <%= link_to 'Edit',
              edit_user_path(user) 
          %>     
          </td>


          <!-- method delete分辨出不同 -->
          <td>
          <%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } 
          %>
          </td>
      
        <%end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/login.html.erb
<%= render 'shared/title', title: 'User Login' %> 

<%= render 'formtag' %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<%= render 'shared/title', title: 'User Resiter' %> 

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %><br>
  <%= @user.email %><br>
  <%= @user.phone %><br>

</p>

<!-- 加入管理者照片 -->


<%= link_to 'Back', users_path %>