config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	#### admin
	#resources :admins
	get 'admins', to: 'admins#index'
	get 'admins/:id', to: 'admins#show', :as => "admin"
	# get 'admins/login', to: 'admins#new'
	# post 'admins/login', to: 'admins#create'
	get 'admins/:id/edit', to: 'admins#edit', :as => "edit_admin"
	patch 'admins/:id', to: 'admins#update'
	delete 'admins/:id', to: 'admins#destroy'

	# login
	get 'login', to: 'admins#login'
	post 'login', to: 'admins#login_create'
	get 'logout', to: 'admins#logout_destroy'
	# -------------------
	#### user
	resources :users
	# match ':users(/:destroy(/:id(.:format)))', via: [:delete]
	match 'users/:id',   :to => 'users#destroy',  :via => 'delete'
	# delete 'users/:id', to: 'users#fuck', :as => "user_fuck"
	# login
	get 'login/users', to: 'users#login', :as => "user_login"
	post 'login/users', to: 'users#login_create'
	get 'logout/users', to: 'users#logout_destroy'
	# -------------------
	#### post
	# resources :posts do
	# 	#### comments
	# 	resources :comments
	# end
	resources :posts

	#### comments
	resources :comments

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :connections
  has_many :categories, through: :connections
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    # Comment.find(1).user
    @comments = @post.comments

    # User.find(16).comments
    # @comments[:user_name] = @post.user
    # binding.pry
    # @post = Post.find(params[:id])
    # Post.find(1).comments
    # @post.comments
    # @comment = Comment.find(@post.id)
  end

  def new
    @post = Post.new
  end

  def create

    #insert user_id into post_params hash
    @post_params=post_params
    @user = User.find(session[:user_id])
    @post_params[:user_id] = @user.id
    #binding.pry
    #@user = Post.find(params[:id]).user
    @post = Post.new(@post_params)
    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      respond_to do |format|
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
      end
    else
      respond_to do |format|
        format.html { render :edit, notice: 'Please update again.' }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/views/posts/_form.html.erb
<div class='well'>

<!-- form_for方法用於產生一個form表單 -->
<%= form_for(@post) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">

      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <!-- 丟參數概念定義class -->
    <%= f.text_field :title %>
  </div>
  <br>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
  <br>

<% end %>

</div>

app/views/posts/_index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'shared/title', title: 'All Post at Here' %>



<!-- Body Post -->

<div id="extra">
  <div class="container">
    <div class="row no-collapse-1">
      <% @posts.each do |post| %>
        <section class="4u"> 
          <a href="#" class="image featured">
            <%= image_tag("pic0"+[1,2,3,4,5,6].shuffle[1].to_s+".jpg") %>
          </a>
          <div class="box">
            <p>
              <h1><%= post.title %></h1><br>
                  <%= post.content %>
            </p>
            <!-- 連結到個別post的button -->
            <%= button_to 'Read More', post_path(post), method: :get 
            %>
            <!-- <a href="#" class="button">Read More</a>  -->
          </div>
        </section>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/title', title: 'Edit Post' %> 

<!-- render呼叫_form.html.erb， -->
<%= render 'form' %>

<!-- <div id="footer" class="wrapper style2">
      <div class="container">
        <section>
          <header class="major">
            <h2>ANY STONEAGE INFORMATION WANT TO SAY？</h2>
            <span class="byline">COME ON！SHARE EVERYONE RIGHT NOW</span>
          </header>

          <form method="post" action="#">
            <div class="row half">

              <div class="12u">
                <input class="text" type="text" name="name" id="name" placeholder="Title" />
              </div>
            </div>
            <div class="row half">

              <div class="12u">
                <textarea name="message" id="message" placeholder="Message">
                </textarea>
              </div>
            </div>
            
            <div class="row half">
              <div class="12u">
                <ul class="actions">
                  <li>
                    <input type="submit" value="Post" class="button alt" />
                  </li>
                </ul>
              </div>
            </div>
          </form>
        </section>
      </div>
    </div> -->

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'shared/title', title: 'All Post at Here' %>



<!-- Body Post -->

<div id="extra">
  <div class="container">
    <div class="row no-collapse-1">
    <!-- form -->
      <% @posts.each do |post| %>
        <section class="4u"> 
          <a href="#" class="image featured">
            <%= image_tag("pic0"+[1,2,3,4,5,6].shuffle[1].to_s+".jpg") %>
          </a>
          <div class="box">
            <p>
              <h1><%= post.title %></h1><br>
                  <%= post.content %>
            </p>
            <!-- 連結到個別post的button -->
            <%= button_to 'Read More', post_path(post), method: :get 
            %>
            <!-- post_path(post,comment) -->
            <%#= button_to 'Read More', post_comment_path(post), method: :get 
            %>
            <!-- <a href="#" class="button">Read More</a>  -->
          </div>
        </section>
      <% end %>
    </div>
  </div>
</div>

<!-- foot bar -->
<% if user_logged_in?%>

<div id="footer" class="wrapper style2">
      <div class="container">
        <section>
          <header class="major">
            <h2>Any StoneAge Information want to say？</h2>
            <span class="byline">Come on！Share everyone right now</span>
          </header>

          
            <div class="row half">
              <div class="12u">
                <ul class="actions">
                  <li>
                    <%= button_to 'Create Post', new_post_path, method: :get 
                    %>
                  </li>
                </ul>
              </div>
            </div>

        </section>
      </div>
</div>

<% else %>

<div id="footer" class="wrapper style2">
      <div class="container">
        <section>
          <header class="major">
            <h2>Any StoneAge Information want to say？</h2>
            <span class="byline">Come on！Share everyone right now</span>
          </header>

          
            <div class="row half">
              <div class="12u">
                <ul class="actions">
                  <li>
                    <%= button_to 'User Login', user_login_path, method: :get 
                    %>
                  </li>
                </ul>
              </div>
            </div>

        </section>
      </div>
</div>

<% end %>

app/views/posts/new.html.erb
<%#= render 'index', post: @post %>

<!-- Post Table Here -->
    <!-- cteate front judgement -->

    <div id="footer" class="wrapper style2">
      <div class="container">
        <section>
          <header class="major">
            <h2>Any StoneAge Information want to say？</h2>
            <span class="byline">Come on！Share everyone right now</span>
          </header>

          <%= form_for(@post) do |f| %>
          <!-- <form method="post" action="#"> -->
            <div class="row half">
              <div class="12u">
              <%= f.text_field :title %>
                <!-- <input class="text" type="text" name="name" id="name" placeholder="Title" /> -->
              </div>
            </div>

            <div class="row half">
              <div class="12u">
                <%= f.text_area :content %>
                <!-- <textarea name="message" id="message" placeholder="Message">
                </textarea> -->
              </div>
            </div>

            <div class="row half">
              <div class="12u">
                <ul class="actions">
                  <li>
                    <%= f.submit %>
                    <!-- <input type="submit" value="Post" class="button alt" /> -->
                  </li>
                </ul>
              </div>
            </div>
          <!-- </form> -->
          <% end %>

        </section>
      </div>
    </div>

app/views/posts/show.html.erb
<!-- post -->
<p>
   <h2><%= @post.title %></h2><br>
   <h4 style="color:#FF8888;">You are viewing <%= @post.title %></h4>
   <div style="background-color:#FF8888;">
   	<h5><%= @post.content %><h5><br>
   	<h5><span style="color:#444444;">post by</span> <%= @post.user.name %><h5>
   </div><br>



</p>

<!-- comment -->
<h4 style="color:#FFDDAA;">Comment Here</h4>
<p>
	<% @comments.each do |comment| %>
	   <div style="background-color:#FFDDAA;">
		   	<h5><%= comment.reply %><h5><br>
		   	<h5><span style="color:#444444;">comment by</span> <%= comment.user.name%><h5> 
	   </div><br>
	<% end %>

</p>

<!-- 加入管理者照片 -->

<%#= link_to 'Edit', edit_post_path(@post) %>
<!-- missing required keys: [:post_id] -->
<%#= link_to 'New Comment', new_comment_path(@post) %>
<% if user_logged_in?%>
	<%= link_to 'New Comment', new_comment_path(@comment) %>
	<%= link_to 'Back', posts_path %>
	<%= link_to 'Edit', edit_post_path %>
	<%= link_to 'Delete', posts_path(@post),
		method: :delete,
	    data: { confirm: 'Are you sure?' } 
	%>
<% end %>